ALTER SESSION SET CURRENT_SCHEMA=VEM_SER;

UPDATE ENDERECO SET cep = '69135-058' , LOGRADOURO = 'Rua dos logradouros' WHERE ID_ENDERECO = 20;

UPDATE ENDERECO SET cep = '69023-003' , LOGRADOURO = 'Alameda dos logradouros' WHERE ID_ENDERECO = 21;

UPDATE ENDERECO SET  NUMERO = 999999 WHERE ID_ENDERECO = 25;

SELECT * FROM ENDERECO;

DELETE FROM ENDERECO WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM ENDERECO);

DELETE FROM ENDERECO WHERE NUMERO = 999999;

SELECT * FROM ENDERECO;

DELETE FROM ENDERECO WHERE ID_ENDERECO = 50 AND ID_ENDERECO = 51;

SELECT * FROM ENDERECO;