-- Right join
SELECT * FROM PESSOA p 
	RIGHT JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA; 

SELECT * FROM PESSOA P 
	RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = pxpe.ID_PESSOA) 
	RIGHT JOIN ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO  = ep.ID_ENDERECO); 


SELECT * FROM PESSOA p 
	RIGHT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA) 
	RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)  
	RIGHT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);


-- Full join
SELECT * FROM PESSOA p 
	FULL JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA; 

SELECT * FROM PESSOA P 
	FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = pxpe.ID_PESSOA) 
	FULL JOIN ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO  = ep.ID_ENDERECO); 


SELECT * FROM PESSOA p 
	FULL JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA) 
	FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)  
	FULL JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);

-- EXISTS

SELECT * FROM PESSOA P WHERE EXISTS (SELECT * FROM ENDERECO_PESSOA ep WHERE p.ID_PESSOA IN ep.ID_ENDERECO);

-- Selecionando id, nome da tabela pessoa e id, logradouro da tabela endereço
SELECT p.ID_PESSOA, p.nome, EP.id_endereco, EP.logradouro FROM PESSOA p 
	LEFT JOIN ENDERECO_PESSOA EP ON (p.ID_PESSOA  = EP.ID_ENDERECO);






